// Signet v0.3 — Hook Enforcement (Signet Enforcement edition)
// OPEN MODULE — Apache 2.0.
//
// Compiles a packet's locks into a lock manifest + a dependency-free
// PreToolUse hook script. On hosts that support hooks (Claude Code),
// the hook denies forbidden tool calls BEFORE they execute and journals
// each denial. `buildEnforcementReceipt` folds the journal into a
// signet-enforcement-receipt-v1 with XAS-CANON-1 dual hashes.
//
// Honest limits, stated once and repeated in docs:
//  - This is NOT a sandbox. It checks declared lock patterns only.
//  - A host without hook support provides no constraint.
//  - Denials carry attribution "hook_intercepted" — the only events
//    Signet describes as enforcement of a running agent.
//
// Matching semantics mirror src/runtime.ts evaluateAction exactly:
// lowercase, strip leading ./, bidirectional substring containment,
// packet strings treated as literals (no regex from packet data).

import { randomBytes } from 'node:crypto';
import type { ParsedPacket, EnforcementReceipt, EnforcementEvent } from './types.js';
import { buildForbiddenSet } from './runtime.js';
import { sha256text, enforcementSha256, enforcementH10 } from './canon.js';

// ── Lock manifest ─────────────────────────────────────────────

export interface ManifestPattern {
  pattern: string;
  source: 'scope.excluded' | 'output_contract.forbidden_outputs';
  lock_id: string;
  lock_rule: string;
}

export interface EnforceManifest {
  manifest_version: 'signet-enforce-manifest-v1';
  packet_id: string;
  packet_sha256: string;
  match_semantics: 'normalized bidirectional substring containment; literals only';
  patterns: ManifestPattern[];
  generated_at: string;
}

/**
 * Compile a packet into a lock manifest. Lock attribution is resolved at
 * compile time (same rule as the simulation runtime: first runtime_enforced
 * lock whose rule text contains the pattern token, else first runtime lock)
 * so the hook script needs no logic beyond matching.
 */
export function compileManifest(packet: ParsedPacket, packetRaw: string): EnforceManifest {
  if (!packet.meta?.id) {
    throw new Error('cannot compile manifest: packet has no META id');
  }
  const runtimeLocks = packet.locks.filter(l => l.type === 'runtime_enforced');
  if (runtimeLocks.length === 0) {
    throw new Error(
      `cannot compile manifest: packet "${packet.meta.id}" declares no runtime_enforced locks — nothing to enforce`);
  }

  const patterns: ManifestPattern[] = buildForbiddenSet(packet).map(fp => {
    const byToken = runtimeLocks.find(l => l.rule.toLowerCase().includes(fp.pattern));
    const lock = byToken ?? runtimeLocks[0];
    return { pattern: fp.pattern, source: fp.source, lock_id: lock.id, lock_rule: lock.rule };
  });

  return {
    manifest_version: 'signet-enforce-manifest-v1',
    packet_id: packet.meta.id,
    packet_sha256: sha256text(packetRaw),
    match_semantics: 'normalized bidirectional substring containment; literals only',
    patterns,
    generated_at: new Date().toISOString(),
  };
}

// ── Hook script template ──────────────────────────────────────
// Written to .signet/hook.mjs by `signet hook init`. Deliberately a
// standalone plain-node script: hooks run as bare commands, so it must
// not require tsx, npm packages, or this repository at call time.
// It resolves enforce.json and journal.jsonl relative to ITSELF, so it
// works regardless of the cwd the host invokes it with.

export const HOOK_SCRIPT = `#!/usr/bin/env node
// Signet enforcement hook (PreToolUse). Generated by \`signet hook init\`.
// Reads one tool-call JSON from stdin. Exit 0 = allow. Exit 2 = deny
// (stderr is fed back to the agent). Denials are appended to journal.jsonl.
// Node builtins only — no dependencies.

import { readFileSync, appendFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

let manifest;
try {
  manifest = JSON.parse(readFileSync(join(here, 'enforce.json'), 'utf-8'));
} catch {
  // Fail open with a loud warning rather than breaking every tool call:
  // a missing manifest means enforcement is not configured, not that
  // all work is forbidden.
  console.error('signet-hook: enforce.json missing or unreadable — call allowed, NOT checked');
  process.exit(0);
}

let input = '';
process.stdin.setEncoding('utf-8');
for await (const chunk of process.stdin) input += chunk;

let call;
try { call = JSON.parse(input); } catch { process.exit(0); }

const toolName = call.tool_name ?? '';
const ti = call.tool_input ?? {};

// Target extraction per tool. File tools → path; Bash → whole command string.
const targets = [];
if (typeof ti.file_path === 'string') targets.push(ti.file_path);
if (typeof ti.notebook_path === 'string') targets.push(ti.notebook_path);
if (toolName === 'Bash' && typeof ti.command === 'string') targets.push(ti.command);

const normalize = (s) => s.toLowerCase().trim().replace(/^\\.\\//, '');

for (const target of targets) {
  const nt = normalize(target);
  if (nt.length === 0) continue;
  for (const p of manifest.patterns) {
    if (!p.pattern) continue;
    if (!(nt.includes(p.pattern) || p.pattern.includes(nt))) continue;

    const event = {
      ts: new Date().toISOString(),
      tool_name: toolName,
      target,
      matched_pattern: p.pattern,
      pattern_source: p.source,
      lock_id: p.lock_id,
      lock_rule: p.lock_rule,
      attribution: 'hook_intercepted',
      decision: 'deny',
    };
    try {
      appendFileSync(join(here, 'journal.jsonl'), JSON.stringify(event) + '\\n', 'utf-8');
    } catch { /* journaling must never turn a deny into a crash */ }

    console.error(
      \`signet-hook DENY [\${p.lock_id}] \${toolName} -> "\${target}" matched "\${p.pattern}" \` +
      \`(\${p.source}). Rule: \${p.lock_rule}. Packet: \${manifest.packet_id}.\`);
    process.exit(2);
  }
}

process.exit(0);
`;

/** The PreToolUse matcher the generated hook is designed for. */
export const HOOK_MATCHER = 'Write|Edit|MultiEdit|NotebookEdit|Bash';

/** Settings snippet for manual installation (printed by `signet hook init`). */
export function settingsSnippet(hookCommand: string): object {
  return {
    hooks: {
      PreToolUse: [
        { matcher: HOOK_MATCHER, hooks: [{ type: 'command', command: hookCommand }] },
      ],
    },
  };
}

/**
 * Merge the Signet hook entry into an existing settings object.
 * Pure function: preserves every existing key and hook; appends only.
 * Idempotent: if the exact command is already registered, returns input unchanged.
 */
export function mergeSettings(existing: Record<string, unknown>, hookCommand: string): Record<string, unknown> {
  const out = { ...existing } as Record<string, any>;
  out.hooks = { ...(out.hooks ?? {}) };
  const pre: any[] = Array.isArray(out.hooks.PreToolUse) ? [...out.hooks.PreToolUse] : [];

  const already = pre.some(entry =>
    Array.isArray(entry?.hooks) &&
    entry.hooks.some((h: any) => h?.type === 'command' && h?.command === hookCommand));
  if (already) return existing;

  pre.push({ matcher: HOOK_MATCHER, hooks: [{ type: 'command', command: hookCommand }] });
  out.hooks.PreToolUse = pre;
  return out;
}

// ── Journal → enforcement receipt ─────────────────────────────

const COVERAGE_STATEMENT =
  'Denials only: allowed tool calls are not recorded. This receipt proves which ' +
  'calls the hook denied — it does not enumerate what the agent was permitted to do, ' +
  'and it provides no evidence about activity on hosts without hook support.';

export function parseJournal(journalText: string): EnforcementEvent[] {
  const events: EnforcementEvent[] = [];
  for (const line of journalText.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      const e = JSON.parse(trimmed);
      if (e && e.decision === 'deny' && e.attribution === 'hook_intercepted') {
        events.push(e as EnforcementEvent);
      }
    } catch { /* skip malformed lines — receipt reflects parseable events only */ }
  }
  return events;
}

export function buildEnforcementReceipt(
  manifest: EnforceManifest,
  journalText: string,
  now: () => Date = () => new Date(),
): EnforcementReceipt {
  const events = parseJournal(journalText);
  const receipt: EnforcementReceipt = {
    receipt_version: 'signet-enforcement-receipt-v1',
    receipt_id: `enf-${now().toISOString().slice(0, 10).replace(/-/g, '')}-${randomBytes(4).toString('hex')}`,
    packet: { id: manifest.packet_id, sha256: manifest.packet_sha256 },
    mode: 'hook_intercepted',
    coverage: COVERAGE_STATEMENT,
    events,
    summary: {
      denials: events.length,
      first_event_ts: events.length > 0 ? events[0].ts : null,
      last_event_ts: events.length > 0 ? events[events.length - 1].ts : null,
    },
    timestamps: { generated_at: now().toISOString() },
    canon: 'XAS-CANON-1',
    hashes: { sha256: '', h10: '' },
    signature: null,
  };
  receipt.hashes.h10 = enforcementH10(receipt);
  receipt.hashes.sha256 = enforcementSha256(receipt);
  return receipt;
}
